"""Add outreach_history table

Revision ID: 86e4fd825eef
Revises: fix_user_settings_fk
Create Date: 2025-11-08 04:19:04.900222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e4fd825eef'
down_revision: Union[str, None] = 'fix_user_settings_fk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('recipient_linkedin_url', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('linkedin_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_history_sent_at'), 'outreach_history', ['sent_at'], unique=False)
    op.create_index(op.f('ix_outreach_history_user_id'), 'outreach_history', ['user_id'], unique=False)
    op.drop_constraint('companies_company_name_key', 'companies', type_='unique')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.drop_index('ix_email_accounts_owner_email_unique', table_name='email_accounts')
    op.drop_constraint('user_settings_user_id_key', 'user_settings', type_='unique')
    op.drop_constraint('user_stats_user_id_key', 'user_stats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_stats_user_id_key', 'user_stats', ['user_id'])
    op.create_unique_constraint('user_settings_user_id_key', 'user_settings', ['user_id'])
    op.create_index('ix_email_accounts_owner_email_unique', 'email_accounts', ['owner_id', sa.text('lower(email::text)')], unique=False)
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_unique_constraint('companies_company_name_key', 'companies', ['company_name'])
    op.drop_index(op.f('ix_outreach_history_user_id'), table_name='outreach_history')
    op.drop_index(op.f('ix_outreach_history_sent_at'), table_name='outreach_history')
    op.drop_table('outreach_history')
    # ### end Alembic commands ###

