"""add_structured_data_to_resume_content

Revision ID: e96eb265e570
Revises: add_job_context_table
Create Date: 2025-11-11 17:16:58.662316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96eb265e570'
down_revision: Union[str, None] = 'add_job_context_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_contexts_job_url'), 'job_contexts', ['job_url'], unique=False)
    op.add_column('resume_content', sa.Column('structured_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_content', 'structured_data')
    op.drop_index(op.f('ix_job_contexts_job_url'), table_name='job_contexts')
    # ### end Alembic commands ###

